// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sieubqtjctkrbgaeyebs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpZXVicXRqY3RrcmJnYWV5ZWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzOTc0NzMsImV4cCI6MjA3MDk3MzQ3M30.8VNRmFdOBf9HnOEcZSea2dXy0O2oA6ZuzdBoXpEnHOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});